In [1]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

# define documents
docs = ['Well done!',
        'Good work'
        'Great effort',
        'nice work',
        'Excellent!',
        'Weak',
        'Poor effort!',
        'not good',
        'poor work',
        'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])

# integer encode the documents
vocab_size = 10
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=None, padding='post')
print(padded_docs)

# define the model
model = Sequential()
model.add(Embedding(vocab_size, 2, input_length=max_length))
# model.add(Flatten())
# model.add(Dense(1, activation='sigmoid'))

# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

# summarize the model
print(model.summary())

C:\Users\Anneke Hidayat\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


[[1, 7], [4, 8, 7], [3, 8], [6], [8], [7, 7], [6, 4], [7, 8], [4, 4, 7, 5]]
[[1 7 0 0]
 [4 8 7 0]
 [3 8 0 0]
 [6 0 0 0]
 [8 0 0 0]
 [7 7 0 0]
 [6 4 0 0]
 [7 8 0 0]
 [4 4 7 5]]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 4, 2)              20        
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________
None


In [2]:
import numpy as np

# model = Sequential()
# model.add(Embedding(1000, 64, input_length=10))
# the model will take as input an integer matrix of size (batch, input_length).
# the largest integer (i.e. word index) in the input should be no larger than 999 (vocabulary size).
# now model.output_shape == (None, 10, 64), where None is the batch dimension.

# input_array = np.random.randint(1000, size=(32, 10))

# model.compile('rmsprop', 'mse')
output_array = model.predict(padded_docs)
# assert output_array.shape == (32, 10, 64)

In [3]:
model.get_weights()

[array([[-0.02619196,  0.03194037],
        [-0.00765017,  0.02035532],
        [-0.03479217, -0.01723608],
        [ 0.00864689,  0.02570535],
        [ 0.03251817, -0.01616557],
        [-0.04700295, -0.02093154],
        [-0.04162155,  0.0295226 ],
        [-0.0463048 , -0.01977211],
        [-0.03724138, -0.03286988],
        [-0.00580846, -0.02814339]], dtype=float32)]

In [4]:
# cos sim

model.get_config()

[{'class_name': 'Embedding',
  'config': {'activity_regularizer': None,
   'batch_input_shape': (None, 4),
   'dtype': 'float32',
   'embeddings_constraint': None,
   'embeddings_initializer': {'class_name': 'RandomUniform',
    'config': {'maxval': 0.05, 'minval': -0.05, 'seed': None}},
   'embeddings_regularizer': None,
   'input_dim': 10,
   'input_length': 4,
   'mask_zero': False,
   'name': 'embedding_1',
   'output_dim': 2,
   'trainable': True}}]

In [13]:
output_array

array([[[ 0.03349861,  0.02965721],
        [ 0.01325924, -0.00041144],
        [-0.02595081, -0.0126145 ],
        [-0.02595081, -0.0126145 ]],

       [[ 0.00664603, -0.01895301],
        [ 0.00664603, -0.01895301],
        [-0.02595081, -0.0126145 ],
        [-0.02595081, -0.0126145 ]],

       [[ 0.00664603, -0.01895301],
        [ 0.03606855, -0.03669266],
        [-0.02595081, -0.0126145 ],
        [-0.02595081, -0.0126145 ]],

       [[ 0.03606855, -0.03669266],
        [ 0.00664603, -0.01895301],
        [-0.02595081, -0.0126145 ],
        [-0.02595081, -0.0126145 ]],

       [[ 0.01927965, -0.04948307],
        [-0.02595081, -0.0126145 ],
        [-0.02595081, -0.0126145 ],
        [-0.02595081, -0.0126145 ]],

       [[ 0.03349861,  0.02965721],
        [-0.02595081, -0.0126145 ],
        [-0.02595081, -0.0126145 ],
        [-0.02595081, -0.0126145 ]],

       [[ 0.01325924, -0.00041144],
        [ 0.03606855, -0.03669266],
        [-0.02595081, -0.0126145 ],
        [-0.0259

In [3]:
output_array.shape

(10, 4, 2)

In [4]:
output_array[0]

array([[ 0.01410856,  0.03978047],
       [-0.00944977,  0.01914482],
       [ 0.01024829,  0.04668455],
       [ 0.01024829,  0.04668455]], dtype=float32)

In [5]:
output_array[1]

array([[-0.03778828, -0.04946722],
       [-0.03778828, -0.04946722],
       [ 0.01024829,  0.04668455],
       [ 0.01024829,  0.04668455]], dtype=float32)

In [8]:
model = Sequential()
model.add(Embedding(25000, 100, input_length=100))
model.add(Flatten()) 
model.add(Dense(1))

In [9]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 100, 100)          2500000   
_________________________________________________________________
flatten_2 (Flatten)          (None, 10000)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 10001     
Total params: 2,510,001
Trainable params: 2,510,001
Non-trainable params: 0
_________________________________________________________________
