In [23]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

# define documents
docs = ['Well done!',
        'Good work',
        'Great effort',
        'nice work',
        'Excellent!',
        'Weak',
        'Poor effort!',
        'not good',
        'poor work',
        'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])

# integer encode the documents
vocab_size = 10
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=None, padding='post')
print(padded_docs)

# define the model
model = Sequential()
model.add(Embedding(vocab_size, 2, input_length=max_length))
# model.add(Flatten())
# model.add(Dense(1, activation='sigmoid'))

# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

# summarize the model
print(model.summary())

[[5, 7], [9, 3], [4, 4], [3, 3], [6], [7], [6, 4], [8, 9], [6, 3], [1, 9, 7, 2]]
[[5 7 0 0]
 [9 3 0 0]
 [4 4 0 0]
 [3 3 0 0]
 [6 0 0 0]
 [7 0 0 0]
 [6 4 0 0]
 [8 9 0 0]
 [6 3 0 0]
 [1 9 7 2]]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_10 (Embedding)     (None, 4, 2)              20        
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________
None


In [24]:
import numpy as np

# model = Sequential()
# model.add(Embedding(1000, 64, input_length=10))
# the model will take as input an integer matrix of size (batch, input_length).
# the largest integer (i.e. word index) in the input should be no larger than 999 (vocabulary size).
# now model.output_shape == (None, 10, 64), where None is the batch dimension.

# input_array = np.random.randint(1000, size=(32, 10))

# model.compile('rmsprop', 'mse')
output_array = model.predict(padded_docs)
# assert output_array.shape == (32, 10, 64)

In [25]:
output_array.shape

(10, 4, 2)

In [26]:
output_array[0]

array([[-0.03375967, -0.02880477],
       [-0.03437487,  0.01339896],
       [ 0.00605009,  0.01652286],
       [ 0.00605009,  0.01652286]], dtype=float32)

In [27]:
output_array[1]

array([[ 0.01612771,  0.01620979],
       [-0.02548026,  0.01423493],
       [ 0.00605009,  0.01652286],
       [ 0.00605009,  0.01652286]], dtype=float32)

In [29]:
model = Sequential()
model.add(Embedding((25000, 100), 3))
model.add(Flatten()) 
model.add(Dense(1))

ValueError: Argument must be a dense tensor: ((25000, 100), 3) - got shape [2], but wanted [2, 2].